### ISSUE TITLE
MIRI workarounds possibly not needed?

### ISSUE THREAD

**Issue by nico-abram** [SabrinaJewson/pinned-aliasable#1]
Since https://github.com/rust-lang/miri/pull/1952 MIRI understands the Unpin workaround, so maybe the MIRI cfg is no longer needed.

That said, to quote RalfJ from that PR:

> >    But can an &Aliasable or &mut Aliasable coexist with an &mut T (or to a field of T)?
> 
> &mut T (with this patch: for T: Unpin) cannot coexist with anything (assuming both pointers are being used). Weakening that guarantee would make it entirely useless for optimizations.
> 
> But &mut T can be reborrowed from &mut Aliasable<T>, as long as for the time that the &mut T is active, no other reference/pointer to that memory is used.

Which seems to contradict the readme:

> so that one &mut Aliasable<T> and either one &mut T or any number of &Ts can coexist

**Comment by SabrinaJewson** [comment]
Thanks for noticing this, I've removed the workaround now - it seems that change was made after I intially wrote this crate.
